### ISSUE TITLE
choose a photo to use from this folder

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-house-psychiatric#10]
to use as the hero image on the site: 

https://drive.google.com/drive/folders/0B_lfcedxYUvffjJGTDltMTRzR0RRblRTU2NEejJxa0xFN1liRk5HRUZFeENGNkNBVHVMcWM

due date:
7-28-15   5p

**Comment by AaronAguilar** [comment]
Think this one would look best: 
https://drive.google.com/open?id=0B_lfcedxYUvfOUpWWktKeDRwcU0
