### ISSUE TITLE
Remove all hero images from the other pages

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-house-psychiatric#12]
and don't replace them with anything.

let's see how it looks and course-correct from there

due date:

7-29-15 11a

**Comment by AaronAguilar** [comment]
Done. http://editllc.github.io/client-house-psychiatric/patients.html

I had to adjust the sidebar because it was touching the navigation.

**Comment by rodneystrong** [comment]
*nods

Good stuff sir. thanks for takin care of this
