### ISSUE TITLE
Add phpmailer form code

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-house-psychiatric#15]
Same way you did it for knot-away.

Don't start this until I've fixed what's wrong with your knot-away mailer code.

due:
9-18-15   5p  (unless I haven't fixed the knot-away code by 8-4-15 11p)

**Comment by AaronAguilar** [comment]
Do I add it now?

**Comment by rodneystrong** [comment]
Yes, please do this now @AaronAguilar

**Comment by AaronAguilar** [comment]
Php code is added on the contact form.
