### ISSUE TITLE
Get aaron the staff photos

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-house-psychiatric#17]
due:
8-5-15  11p

**Comment by rodneystrong** [comment]
Yo @AaronAguilar , here's the link: https://drive.google.com/folderview?id=0BzVFl2mibGTnMF9UUklRdWdXRDA&usp=sharing

Let me know if you have problems downloading them.

**Comment by AaronAguilar** [comment]
Downloaded and implemented them.

**Comment by AaronAguilar** [comment]
Some people do not have images, such as "Lana Williams", "Laura Slippy", and "Margaret House.
"

**Comment by AaronAguilar** [comment]
http://editllc.github.io/client-house-psychiatric/staff.html

Everyone is linked but Laura. There is also another extra person they have on their website, "Paul Haluak" but it's not include on their Staff page but as a sub-page.

**Comment by rodneystrong** [comment]
Gotcha, I'll contact the client about this.
