### ISSUE TITLE
Remove sidebar from staff page

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-house-psychiatric#19]
remove the sidebar from the 'staff' page.

not sure if i want to do the same for all the individual staff pages as well...

why don't you try that also and see if you like it or not. if you're unsure, take a screenshot and post it here.

due:
8-11-15  11a

**Comment by AaronAguilar** [comment]
It's removed. http://editllc.github.io/client-house-psychiatric/staff.html

We talked about using a different sidebar for individual staff pages. The issue can be found here: https://github.com/EditLLC/client-house-psychiatric/issues/20

**Comment by rodneystrong** [comment]
Gooood stuff
