### ISSUE TITLE
Individual staff pages

### ISSUE THREAD

**Issue by AaronAguilar** [EditLLC/client-house-psychiatric#20]
Create a redesign for individual staff pages that include headers "Education" and "Specialities". Also have a left sidebar that includes the image of the staff member and patient contact information. 

Due date: 
8-10-15 11 pm

**Comment by rodneystrong** [comment]
@AaronAguilar thanks for creating this.

**Comment by AaronAguilar** [comment]
@rodneystrong No problem! 

Question, however, some bios don't have enough information. For example, http://editllc.github.io/client-house-psychiatric/staff/ani-tokat.html does not have enough information to fill in the fields of Medical School, Internship, and Residency. 

Some field had to be changed, for example nurses, http://editllc.github.io/client-house-psychiatric/staff/susan-davin.html -- in which they didn't go to a medical school but they did go to different schools and have had a similar job priviously. 

Is it okay to make these adjustments?

**Comment by rodneystrong** [comment]
Yea go ahead and good suggestion. 

I'll try to find out what I can for Dr. Tokat.

**Comment by rodneystrong** [comment]
Ok I've got one of their office staff collecting bio info for us. Soon you'll have all the info you need.

**Comment by rodneystrong** [comment]
The office admin is still trying to round up staff bio content.

**Comment by rodneystrong** [comment]
fyi now the office admin + sherry are tryin to round up staff bios as well. will update this issue when the bios get in.
