### ISSUE TITLE
News archive pages

### ISSUE THREAD

**Issue by AaronAguilar** [EditLLC/client-house-psychiatric#22]
@rodneystrong 
Do you like the current design for it? http://editllc.github.io/client-house-psychiatric/news.html

Instead of creating a separate page that lists post for only say, June 2010, which would only be one or two posts, I made it anchor to the ID of that said date. 

So when they click on the date on the drop down news archive it'll take them to that date on the News page.

**Comment by rodneystrong** [comment]
I do! Let's add appropriate images to blog posts that merit them. 

You know how they have a post on Kathie Spriggs? Put her picture there in the archive list. 

Same thing with Sherry and any other posts that relate to the staff and/or you have a picture in mind that could go with the post.

In terms of layout, let's add some spacing in between each post. My 1st guess would be 30px or so, but i trust you to tweak it well.

Good job so far!

**Comment by AaronAguilar** [comment]
I'm adding the images, but here's what they'd looked like. http://editllc.github.io/client-house-psychiatric/news/kathie-spriggs.html

Would you want the images to be on the side of text or just in the center? 

Added the padding to the layout, too ;D

**Comment by rodneystrong** [comment]
Yaay! ;D

The way you have it (images on side) is the way I prefer it. Good stuff. Thank youuuuuu
