### ISSUE TITLE
hover issue

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-house-psychiatric#24]
![hover](https://cloud.githubusercontent.com/assets/539962/9258071/249ed28e-41ae-11e5-8ab4-4ae48b9a34d6.jpg)

When you hover over a month, the whole width of the item doesn't change color. Please make it span the whole width

due: 
8-14-15  3p

**Comment by AaronAguilar** [comment]
Fixed. http://editllc.github.io/client-house-psychiatric/news.html

**Comment by rodneystrong** [comment]
Good stuff good stuff! 

I like transition speed of the hover as well. good job dude.
