### ISSUE TITLE
Create placeholder image

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-house-psychiatric#25]
Some therapists do not have an image and will NOT have a photo taken, so please create a placeholder image that has the same dimensions as the other images. 

Make it an avatar of a default person. 

Put this placeholder into the areas where people are missing a photo.

due:
8-14-15   4p

**Comment by AaronAguilar** [comment]
Done. It has the words, "no image available." with a low opacity, but it's a medical avatar. 

http://editllc.github.io/client-house-psychiatric/staff.html

**Comment by rodneystrong** [comment]
Thanks for creating this. Let's go a different direction though.

Instead of using the doctor avatar, just use a generic person avatar, make it a dark grey, and put it on a light grey background. Then have the letters HPC below the avatar in the same font as the HPC logo. 

Thanks!

due: 
8-18-15   3p

**Comment by AaronAguilar** [comment]
Added and pushed. You could see it on the staff page.

**Comment by rodneystrong** [comment]
GOOOD good good, definitely in the right direction. I dont like the way the avatar looks cause it reminds me of the Roswell alien, but we'll use it for now.

**Comment by AaronAguilar** [comment]
Two new avatars -- 
Male: https://drive.google.com/open?id=0BwNEeMVrMpDLMThLTDRxSk5lTDQ
Female: https://drive.google.com/open?id=0BwNEeMVrMpDLdXlFSjMtSzFpbDQ
