### ISSUE TITLE
Remove neurospsychology as a service and replace with yoga

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-house-psychiatric#26]
Go to the 'services' page and remove the "Neuropscyhology" link and the page as well. 

Replace it with "Yoga Classes", content for the page to come soon.

due:
9-4-15   5p

**Comment by AaronAguilar** [comment]
Updated.

**Comment by rodneystrong** [comment]
Please fix this, the link to Neuropscyhology is still there as well as the icon. 

9-15-15    3p

**Comment by rodneystrong** [comment]
@AaronAguilar  also, 'Neuropsychological Testing' is still present in the footer on the staff.html page. please fix this with the same due date in the previous comment

**Comment by AaronAguilar** [comment]
Sorry about that, I thought I had saved it last time, but it's updated.

**Comment by rodneystrong** [comment]
>:(    always double-check your work @AaronAguilar !!  ;D
