### ISSUE TITLE
Client noticed these issues

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-house-psychiatric#29]
Client emailed me noting these issues:

- Home page: typo under the "we'll give you a call" section

- Services tab: remove "Geriatric"  "Adoption Evaluations" "Intensive Treatment" "Testing Services";  Move "Medicine" to the top row; Change "Yoga Classes" to "Relaxation Training" 

- Side bar: Remove insurance forms from the side bar (move to New patient page)

- Order the tabs: Home, Services, New Patient, Staff, Bill Pay

- Check the map alignment under the Contact Us section

due:
9-22-15  4p

**Comment by AaronAguilar** [comment]
Updated!

**Comment by rodneystrong** [comment]
nice nice very nice
