### ISSUE TITLE
Start coding from these mockups

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-house-psychiatric#3]
Bootstrap pls ty.

5 pages, coded to look as close as possible to these mockups:

![staff-01](https://cloud.githubusercontent.com/assets/539962/8790725/04870ea4-2f06-11e5-8a3d-72eb6000bb6b.jpg)
![contact-us-01](https://cloud.githubusercontent.com/assets/539962/8790726/048a0a5a-2f06-11e5-81af-7606de089a22.jpg)
![Uploading home-01.jpg…]()
![patients-01](https://cloud.githubusercontent.com/assets/539962/8790727/048b10c6-2f06-11e5-920f-5b2cb0c3fcbe.jpg)
![services-01](https://cloud.githubusercontent.com/assets/539962/8790729/048dda9a-2f06-11e5-9e68-95551d375e50.jpg)

These are also available in the Drive folder.

Due date: 
7-24-15 10p

**Comment by purplyrocky** [comment]
@rodneystrong, I asked aaron for the big images, he said you have them.
@AaronAguilar I need the icons

putting it here so you guys don't forget

**Comment by rodneystrong** [comment]
@purplyrocky big images? are you referring to the stock images he's using in his mockups?

**Comment by purplyrocky** [comment]
@rodneystrong yes

**Comment by rodneystrong** [comment]
@purplyrocky Hmm.. @AaronAguilar I don't recall having them. How did you get them into your mockups? Could you just upload them into the correct buildicus folder for us please?

**Comment by purplyrocky** [comment]
@rodneystrong oh welllllllll guess i gotta use kittens! (for now)

**Comment by AaronAguilar** [comment]
I uploaded the images they have as well as a stock image.

**Comment by purplyrocky** [comment]
Is this site going to be more than 5 pages? there are a lot of links in the bottom nav and i'm not sure where some of them lead. Also, there are a lot of icons on the "services" page and i don't know where to point those either.
@rodneystrong
@AaronAguilar

**Comment by AaronAguilar** [comment]
I'm not entirely sure how many other pages there will be. I know for the home pages there's some news pages that take you somewhere. The navigation at the bottom are just regular links to pages that you'll already have up, except for some such as Mission & Values which should probably direct them to about us?

**Comment by purplyrocky** [comment]
yeah it's basically the group of links under "services" in the footer and the icons on the services page that i'm not sure of.

**Comment by purplyrocky** [comment]
still working on this, still need to do the contact and staff page. maybe another hour of work
