### ISSUE TITLE
meeting with sherry 9-23-15 

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-house-psychiatric#31]
- make it a monthly newsletter, not a weekly

- remove white space gap on home page

- Sherry is figuring out a content strategy in terms of blogging, but we agreed that 

- for the copy, ways to make it more personal, use "we" pronouns instead of referring to itself in the 3rd person

- for the staff photo, everyone's here on thursday. 

- remove adhd/add, second opinions from the 'services' page (we'll get the copy for the other services from Sherry by Friday)

- change 'family therapy' to family and couples therapy'

- Make the "insurance forms" say "New patient forms" 

- include staff photo at the top of "staff page" 

- on the 'contact us' page, replace the word 'widget' with something more user-friendly 

- for the "logo" use the full name "House psychiatric clinic" or "House clinic" (try full name if possible)

- 'home' page, the 'about us' section doesn't add much value, so remove the content in the box in the hero image, and then move the content from "about us" to the box. Replace "Check out our services" to "Meet our staff" and link to staff page

- be more accessible and personable to the community is our goal

- sherry's ok with the site going live with the current hero image, but i gotta figure out a different hero image on home page

**Comment by rodneystrong** [comment]
A better explanation of what needs to be done:
http://screencast-o-matic.com/watch/coQT3TfLuN

due:
9-28-15  1p

**Comment by AaronAguilar** [comment]
Updated. 
Still need
- blogging situation 
- staff (group?) photo
- new services 
- new hero image

**Comment by rodneystrong** [comment]
Got the final bio!
"Thanks, Alex.  Sue also sent hers to me on Friday night.  It's below, and it's for Sue Harrington-Howard, FNP-C, PA-C. Her words to me were "OK - we are going for minimalistic"  :)

Thanks!
Cherie
Please use the following as Sue's bio:

Education
Fresno City College - AA,AS, RN
U.C. Davis FNP Certificate, PA Certificate
California State Dominguez Hills - B.S - Nursing

Sue has worked in the medical field in Fresno for over 40 years. She has a wide variety of experience including Primary Care, Substance Abuse, and Psychiatric Management. Her focus has been to work with medically underserved populations."

Also, here's the staff photo: https://drive.google.com/a/editllc.com/file/d/0B88_mCI0OTGkcF9RdXdwekpFcmc/view?usp=sharing

due:
10-5-15   11p

**Comment by AaronAguilar** [comment]
Updated -- 

Is that all their staff? I might have more staff pages. Can I get an updated list of all their staff? I recognized everyone but three women, which do not have pages unless they do but do not have an image. If that all makes sense. 


People that do not have information --

Laura Slippy, Paul Hulak, Margaret House, Kathie Spriggs, and Justin Wallace.

**Comment by rodneystrong** [comment]
@AaronAguilar ok i removed paul hulak but i'll put the rest of the staff updates here as I get them.

**Comment by AaronAguilar** [comment]
@rodneystrong Okay. I'm going over the site at the moment and making sure that everything looks good.

**Comment by rodneystrong** [comment]
"Justin just got back to me about his bio. Please use the following blurb for his profile:

Justin Wallace, MFTi, is an intern whose interests include spirituality, physical fitness, and working with adults and adolescents from an eclectic perspective.

Thank you so much!"

due:
10-7-15    5p

**Comment by AaronAguilar** [comment]
Updated: 
http://editllc.github.io/client-house-psychiatric/staff/justin-wallace.html

**Comment by rodneystrong** [comment]
good stuff, thank you sir
