### ISSUE TITLE
Updated copy for the site

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-house-psychiatric#32]
Here's a link to the copy that the client wants on the website. Please update this on the gh-pages branch.

https://docs.google.com/a/editllc.com/document/d/1Vx0Hn9PE_7dSOfje-M79bbsmy7a8H-1_oskr-JNycLM/edit?usp=sharing

due: 
9-29-15   5p

**Comment by AaronAguilar** [comment]
Updated services.
http://editllc.github.io/client-house-psychiatric/index.html

**Comment by rodneystrong** [comment]
good shit aaron, thanks for taking care of this. lotsa' tedious content change so i appreciate it.
