### ISSUE TITLE
Fix the newsletter signup on Contact page

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-house-psychiatric#33]
http://editllc.github.io/client-house-psychiatric/contact.html

It's off.

due:
10-6-15  3p

**Comment by rodneystrong** [comment]
Is this done?

**Comment by AaronAguilar** [comment]
No, sorry. I had it done yesterday but I just figured out how to include a glyphicon inside the placeholder so I'm incorporating that.

**Comment by AaronAguilar** [comment]
Updated.

**Comment by rodneystrong** [comment]
nice work sir
