### ISSUE TITLE
Add the data-size="compact" attribute to all the class="recaptcha" tags

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-house-psychiatric#34]
There's about 6 pages you gotta add this to for the Google recaptcha. 

due:
10-7-15     10a

**Comment by AaronAguilar** [comment]
Here's the push for trying to use JavaScript - 07a01d889619841f05a59c3de5c086cbef40c480

Otherwise all pages are compact.

The home page has some spacing betweens the Newsletter and About icons

**Comment by AaronAguilar** [comment]
Updated with help from Joel

**Comment by rodneystrong** [comment]
I just tested this out and even on refresh after resizing the recaptcha block doesn't seem to be resizing. Not sure what happened, but for now I've commented out the JS on the home page and added the data-size attribute directly on the tag to be compact.

**Comment by rodneystrong** [comment]
For this, let's make the recaptcha permanently compact, since the large size extends beyond the sidebar. 

Please have this updated by tomorrow morning 11a.

**Comment by AaronAguilar** [comment]
updated and ftp'd.

**Comment by rodneystrong** [comment]
Excellent sir, thank you
