### ISSUE TITLE
Document all links

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-house-psychiatric#35]
Go to the current live site and look at the URLs for ALL thelinks in the main nav. Document them in a google doc and save it into our google drive. 

Here's an example of a few lines:
"Staff" link: http://www.housepsychiatricclinic.com/fresno-therapists-psychiatrists/

"Matt House, D.O." link: http://www.housepsychiatricclinic.com/fresno-therapists-psychiatrists/matt-house-d-o/

due:
10-7-15       2p

**Comment by AaronAguilar** [comment]
Done -

https://docs.google.com/document/d/1t1X5JeQ7SIhm2lxcwmRISjMm60dThDY6xPcbrlgr9-w/edit?usp=sharing

I added headers to make it easier to identify in what folder they're in.

**Comment by rodneystrong** [comment]
So glad you did. Thanks for this.
