### ISSUE TITLE
Site updates from client

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-house-psychiatric#37]
From Sherry:

-I think we've misspelled "Psychiatric" on the Home Page link to the services tab

-The text under services should read: House Psychiatric Clinic is a full service outpatient mental health clinic. Whether you are struggling with general issues of living, marital problems, or major psychiatric concerns, we would love to support your overall mental health.
We offer general services for patients of all ages and we strive to offer the services our community needs.

-Under "Services" Slide scale should be Sliding Scale

Under "news" let's add this:

Need a little more calm in your life? Consider joining one of our relaxation training groups. These 3-4 session programs can help you use your breath, body, and brain to pursue a happier, more focused life. Groups are currently offered at 9AM on Tuesdays, 11AM on Thursdays. We hope to add a Tuesday evening group in November. 

You can use my photo with this "news" or a generic meditation or yoga type image.

due:
10-15-15   12p

**Comment by AaronAguilar** [comment]
Updated due date - 10-15-15 9P

What do you mean by "Sliding Scale" for the Services page?

**Comment by rodneystrong** [comment]
What do you mean "what do i mean" ? 
I think it's exactly what she said. Under "Services" the text slide scale should be Sliding Scale.

**Comment by AaronAguilar** [comment]
Ohh, I'm sorry. I thought you meant sliding like, the effect, sliding. My apologies, I always associated the Treehouse program with the treehouse program and not the Sliding Scale.

**Comment by AaronAguilar** [comment]
Could you upload the logo?

**Comment by AaronAguilar** [comment]
Updated. 
The Image used in the Yoga news section is - https://pixabay.com/en/yoga-workout-exercise-stretching-263673/

The content underneath the 'Services' tab on the Home-page is long. Is there something they'd like to add to the other spaces to fill it up? I'll come up with some longer text for the moment.

**Comment by rodneystrong** [comment]
![hpc-logo](https://cloud.githubusercontent.com/assets/539962/10555964/81caee56-742c-11e5-9416-8c00c1b2e53d.jpg)

It's a jpg, so you're gonna have to remove the white color and convert it to png. 

With regard to the "services" section on the home page, put this sentence under the "New patients" section: We offer general services for patients of all ages and we strive to offer the services our community needs.

**Comment by AaronAguilar** [comment]
Updating menu now and triple checking the entire site.

**Comment by AaronAguilar** [comment]
Done.
