### ISSUE TITLE
Add Melissa Wagner to staff

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-house-psychiatric#38]
She's a psychologist
![mellissa wagner-profile](https://cloud.githubusercontent.com/assets/539962/10503855/0350c20e-72af-11e5-8b22-1ff4ceaf16f2.jpg)

No bio as of yet, but this photo up there and then add the label "Waiting on client" to this issue once you're done.

due:
10-15-15   12p

**Comment by AaronAguilar** [comment]
Updated!

**Comment by rodneystrong** [comment]
good stuff!

now can you create a placeholder page for her? i know we don't have a bio yet but just put in the template you currently have for the other therpists but with empty content. 

Also, put  "Psy.D" next to her title on Psychiatry.

**Comment by AaronAguilar** [comment]
Update - this has been up, just waiting on client for info.
