### ISSUE TITLE
Online bill pay link

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-house-psychiatric#39]
Create a page for it. Make it the same template as the 'new patients' page but with the text "Not available yet".

due:
10-20-15    6p

**Comment by AaronAguilar** [comment]
Updated. All pages link to the new page.

**Comment by rodneystrong** [comment]
This still doesn't seem to be FTP'ed, so please comment here again when it's updated on the live site.

**Comment by AaronAguilar** [comment]
This is FTP'd
