### ISSUE TITLE
fix toggle nav

### ISSUE THREAD

**Issue by purplyrocky** [EditLLC/client-house-psychiatric#4]
when re-sized down, the toggle button to display the nav shows up but the nav doesn't drop down when clicked.

@rodneystrong just a heads up, I'm going to assign myself to this but if i can't fix it by tonight at midnight, I will reassign it to you, sry. I'm pretty sure I can fix this, but I've already spent a few hours on it.

**Comment by rodneystrong** [comment]
hmm.. have you checked what errors your console is giving you? 

good luck, keep it up. no worries if you have to pass it to me to review.

**Comment by purplyrocky** [comment]
No errors! haha

**Comment by rodneystrong** [comment]
Ah ok, then it's most likely that the nav bar is missing content (like some <li>'s)

I'll check it out tonight regardless.
