### ISSUE TITLE
changes/errors from the client

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-house-psychiatric#41]
Staff Page for Adam Ghali
School: (Put each degree on its own line).
              Add: MA in Theology from Fuller Theological Seminary.
Training/Internship:
Kern County Mental Health, Bakersfield, CA
Kaiser Permanente Behavioral Health, Bakersfield, CA
Bio:
Dr. Ghali is a postdoctoral Psychological Assistant who works part time at House Psychiatric Clinic. He is also an Assistant Professor of Marriage and Family Therapy at Fresno Pacific University. Dr. Ghali works with individuals, couples, and families from a variety of theoretical perspectives. His interests include faith and spirituality, men's health, and life transitions.
 
Also:
The Psychotherapy page has a typo: It’s currently spelled: Pyschotherapy
 
Sometimes the light blue or light green on white background is too light. It’s hard to see.
 
New Patients Tab: The form: “Privacy policy 2010-2011” makes us look outdated
 
The “meet our staff” button on the homepage links to the “services” page

due:
10-20-15   10p

**Comment by AaronAguilar** [comment]
Updated -- 
-Used a darker hue of blue and green for text so that it'll be easier to read. 
-Took off year on the policy forms
-meet our staff button now links to staff

**Comment by rodneystrong** [comment]
These aren't FTP'ed onto the live site, so please comment here again when they are. Remember the due date time.

**Comment by AaronAguilar** [comment]
This is FTP'd.

**Comment by rodneystrong** [comment]
thank you sir
