### ISSUE TITLE
updates and error from client

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-house-psychiatric#42]
>one of the girls in our call center can click the phone number and it pulls up a window that says something about making a call to the office. The phone number listed there in the pop-up window is 266-1316 instead of 226-1316.  If it's easier to correct this by just taking off the option of calling us by clicking that link, that is totally fine.  The number for contacting us is correct until you click the link and the window pops up.

___________________________________________________________

>The last thing has to do with two of our nurses. One of the, Sue HH, has also rewritten her bio. I will wait on the bio she would like to use to replace her old bio, and I'll send it once she sends me her new picture.  Would it be possible, though, to change their professional designations?  Sue's name should read like this:

Sue Harrington-Howard, FNP-C, PA-C.

Susan's should say PMHNP-BC.

due:
10-22-15    5p

**Comment by AaronAguilar** [comment]
Done and FTP'd

**Comment by rodneystrong** [comment]
good work hombre. but please go back and remove the period pictured at the end:

<img width="239" alt="screen shot 2015-10-23 at 12 09 56 am" src="https://cloud.githubusercontent.com/assets/539962/10686678/50ae8fd2-791b-11e5-9f90-53efffb128bd.png">

**Comment by AaronAguilar** [comment]
Fixed and FTPing
