### ISSUE TITLE
Add to the default text in the message box for the contact

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-house-psychiatric#43]
>I wanted to see if we could change the blurb in the box of the email to ask patients for a little more information. Right now, we're getting some messages that state just the patient's name, number, and days of the week. I don't think the people sending the email know that they can write something more than those things.  I think if the little message in the box said something like: 

>Please tell us a little bit about the reason you'd like an appointment.  Please include your name and phone number so we can contact you, and let us know what insurance you're using so we know which of our providers can see you.

>It might encourage people to write a little bit more, and will also help our receptionist better understand what the person needs when they call them back.  Would this be okay?

due:
10-23-15  2p

**Comment by AaronAguilar** [comment]
Done and FTP'd

**Comment by rodneystrong** [comment]
ty sir!
