### ISSUE TITLE
New blog post

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-house-psychiatric#44]
>Hi Alex,

Could you post this article to the "news" section on the HPC website?

http://m.huffpost.com/us/entry/562fa500e4b06317990f8754

Heading: Why is there yoga at your psychiatrist's office?

Thanks!

Aaron, I followed up with the client to see how exactly she wants us to post this on the site. Reason being is that I dont know if we can directly copy/paste that Huff post article onto the HPC site, much less that top image as well. 

In the mean time, just find another generic public domain yoga photo, post the link to where you got that photo in the comment here, and then create this post with the first 100 words or so as a snippet and end with a 'read more' anchor tag that links directly to the Huff Post article (essentially the same format you did for the other blog posts). Oh and also use the heading/title she suggested.

Let me know if I wasn't clear. 

due:
11-5-15     6p

updated due:
11-6-15   5p

**Comment by AaronAguilar** [comment]
Done and FTP'd.

**Comment by rodneystrong** [comment]
Thank you sir. I'll keep this open once I hear from the client.

**Comment by rodneystrong** [comment]
Client wrote back. Here's what they want:

Let's link to the article with this little blurb:

Why is your psychiatrist's office including yoga as a treatment option? 

It's all about the science. New research is making a strong case for yoga and mindfulness practices as important tools in the struggle against stress and anxiety. A regular relaxation practice can help reduce the most troubling symptoms of depression and anxiety. Yoga is also used as a treatment for trauma-related problems. These calming techniques have also been shown to reduce general health problems and are helping communities save money by decreasing visits to the emergency room. 

As a bonus, yoga-based relaxation feels great and is fun! 

Our staff is leading the Valley in the integration of yoga and mindfulness into cutting edge psychiatric care. Contact us to learn more about the relaxation programs that we offer.

due:
11-6-15  5p

**Comment by AaronAguilar** [comment]
Updated.

**Comment by rodneystrong** [comment]
good job sir. i like how you did the preview and the full post too.
