### ISSUE TITLE
Update Justin's bio

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-house-psychiatric#45]
FTP into our server and copy/paste the housepsychiatricclinic.com site onto your local drive. 

Same process as you did with sublimetimefun.com. 

Go to justin's page in the "staff" folder and update his bio with this text:

>Justin Wallace, MS, is a Marriage and Family Therapy Registered Intern with interests in spiritual wellness and physical fitness.  He works with adults and adolescents from a wide variety of approaches.

due:
11-16-2015   12p

**Comment by rampage1213** [comment]
done
