### ISSUE TITLE
Fix footer font

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-house-psychiatric#9]
![font](https://cloud.githubusercontent.com/assets/539962/8944167/d221ca24-3533-11e5-9481-b8425b81a494.jpg)

Please make the footer font the same as the font for the rest of the site

due date:
7-28-15   5p

**Comment by AaronAguilar** [comment]
On the actual website and not the mockup, correct?

**Comment by rodneystrong** [comment]
correct, that screenshot was taken from the actual gh-pages site

**Comment by AaronAguilar** [comment]
Here it is. http://editllc.github.io/client-house-psychiatric/

**Comment by rodneystrong** [comment]
Excellent work sir. One small problem, please use px instead of pt for the unit of measure. 

Keep it at 14 though. So it should be "14px"

**Comment by AaronAguilar** [comment]
Done! Even used a converted to figure out the correct pixels. ;)

**Comment by rodneystrong** [comment]
@AaronAguilar unfortunately the gh-pages branch doesn't reflect the 14px font-size needed for the footer links. 

Please update the gh-pages branch to reflect this then comment here. Thanks!

**Comment by AaronAguilar** [comment]
Done, changed from 18px to 14 px and changed the h3 tags to h4.

**Comment by rodneystrong** [comment]
*nods  I knew i could rely on you.

Thanks!
